version: '2'
services:
 web:
    build: web
    ports:
      - "5000"
    volumes:
     - share:/sharedvol/
    links:
     - pgdb
 pgdb:
    build: db
 rabbit:
    build: rabbit/new/
    hostname: foo
    environment: 
     - CLUSTER_WITH=rabbit
    networks: 
     - rabbitnet

volumes:
 share: {}

networks:
 sharenet: {}
 rabbitnet: {}
